/* node queens-tools/build.js — writes queens-site/levels.js.
   Every puzzle is generated, then re-verified from its codec string before
   it is allowed into the file. */
const fs = require('fs');
const path = require('path');
const C = require('./core.js');

// level count per (size, band), ramped from small and gentle to big and mean
const PLAN = [
  [7, 0, 22], [7, 1, 16], [7, 2, 6],
  [8, 0, 20], [8, 1, 16], [8, 2, 8],
  [9, 0, 14], [9, 1, 14], [9, 2, 10],
  [10, 0, 8], [10, 1, 10], [10, 2, 6],
];
const POOL_PER_BUCKET = 5;   // spare puzzles the page falls back on in Random mode
const BAND_NAME = ['easy', 'medium', 'hard'];

const rnd = C.makeRng(20260908);
const seen = new Set();

function collect(N, band, want, label) {
  const out = [];
  const t0 = Date.now();
  let tries = 0;
  while (out.length < want) {
    tries++;
    if (tries > 400000) throw new Error('gave up on ' + label);
    const p = C.makePuzzle(N, rnd);
    if (!p || p.band !== band) continue;
    const key = Array.from(p.regions).join('');
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(p);
  }
  out.sort((a, b) => a.score - b.score);
  console.log('  ' + label.padEnd(16) + out.length + ' puzzles, ' + tries + ' tries, ' +
    ((Date.now() - t0) / 1000).toFixed(1) + 's, score ' + out[0].score + '-' + out[out.length - 1].score);
  return out;
}

console.log('building campaign');
const campaign = [];
for (const [N, band, want] of PLAN) {
  campaign.push(...collect(N, band, want, N + 'x' + N + ' ' + BAND_NAME[band]));
}

console.log('building spare pool');
const pool = {};
for (const N of [7, 8, 9, 10]) {
  pool[N] = [];
  for (let band = 0; band < 3; band++) {
    pool[N].push(collect(N, band, POOL_PER_BUCKET, 'pool ' + N + 'x' + N + ' ' + BAND_NAME[band]));
  }
}

// ------------------------------------------------- re-verify from the codec
console.log('re-verifying every puzzle from its codec string');
let checked = 0;
const check = p => {
  const s = C.encode(p);
  const d = C.decode(s);
  if (C.encode(d) !== s) throw new Error('codec round-trip failed: ' + s);
  if (C.countSolutions(d.N, d.regions, 3) !== 1) throw new Error('not unique: ' + s);
  if (!C.verify(d)) throw new Error('stored answer is not the solution: ' + s);
  const r = C.rate(d.N, d.regions);
  if (!r.solved) throw new Error('needs guessing: ' + s);
  if (r.band !== d.band) throw new Error('band drifted: ' + s);
  checked++;
  return s;
};

const campaignStrings = campaign.map(check);
const poolStrings = {};
for (const N of Object.keys(pool)) poolStrings[N] = pool[N].map(list => list.map(check));
console.log('  ' + checked + ' puzzles verified unique and guess-free');

// ------------------------------------------------------------------- write
const lines = [];
lines.push('/* Kitchen Table Queens — puzzles, generated by queens-tools/build.js.');
lines.push('   Each string is  size|colours|answer|difficulty|effort .');
lines.push('   Every one was re-checked for a single solution before it was written. */');
lines.push('(typeof window !== "undefined" ? window : globalThis).QUEENS_LEVELS = {');
lines.push('  campaign: [');
for (const s of campaignStrings) lines.push('    "' + s + '",');
lines.push('  ],');
lines.push('  pool: {');
for (const N of [7, 8, 9, 10]) {
  lines.push('    "' + N + '": [');
  for (const band of [0, 1, 2]) {
    lines.push('      [' + poolStrings[N][band].map(s => '"' + s + '"').join(', ') + '],');
  }
  lines.push('    ],');
}
lines.push('  },');
lines.push('};');
lines.push('if (typeof module === "object" && module.exports) module.exports = globalThis.QUEENS_LEVELS;');
lines.push('');

const target = path.join(__dirname, '..', 'levels.js');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, lines.join('\n'));

const bandsBySize = {};
for (const p of campaign) {
  bandsBySize[p.N] = bandsBySize[p.N] || [0, 0, 0];
  bandsBySize[p.N][p.band]++;
}
console.log('\nwrote ' + target);
console.log('  campaign ' + campaignStrings.length + ' levels, ' + (fs.statSync(target).size / 1024).toFixed(1) + ' kB total');
for (const N of [7, 8, 9, 10]) console.log('    ' + N + 'x' + N + '  easy/med/hard ' + bandsBySize[N].join('/'));
console.log('  spare pool ' + Object.values(poolStrings).flat(2).length + ' puzzles');
