/* node queens-tools/build.js — writes queens-site/levels.js.
   Every puzzle is generated, then re-verified from its codec string before
   it is allowed into the file. */
const fs = require('fs');
const path = require('path');
const C = require('./core.js');

// level count per (size, band), ramped from small and gentle to big and mean
const PLAN = [
  [7, 0, 22], [7, 1, 16], [7, 2, 6],
  [8, 0, 20], [8, 1, 16], [8, 2, 8],
  [9, 0, 14], [9, 1, 14], [9, 2, 10],
  [10, 0, 8], [10, 1, 10], [10, 2, 6],
];
// Random mode falls back on these when it cannot make a board inside its
// budget, which for a 10x10 Hard is most of the time, so the bucket has to be
// deep enough that she does not see the same board twice in a sitting.
const POOL_PER_BUCKET = 14;
const BAND_NAME = ['easy', 'medium', 'hard'];

const rnd = C.makeRng(20260908);
const seen = new Set();
const timing = [];

function collect(N, band, want, label) {
  const out = [];
  const t0 = Date.now();
  let tries = 0;
  while (out.length < want) {
    tries++;
    if (tries > 400000) throw new Error('gave up on ' + label);
    // Generating to the band, not filtering afterwards: the size floor and the
    // evening pass are part of what the band means now.
    const p = C.makePuzzle(N, rnd, { band });
    if (!p || p.band !== band) continue;
    const key = Array.from(p.regions).join('');
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(p);
  }
  out.sort((a, b) => a.score - b.score);
  const ms = (Date.now() - t0) / out.length;
  timing.push({ N, band, n: out.length, tries, ms, label });
  console.log('  ' + label.padEnd(18) + String(out.length).padStart(3) + ' puzzles, ' + String(tries).padStart(7) + ' tries, ' +
    ((Date.now() - t0) / 1000).toFixed(1).padStart(6) + 's, ' + ms.toFixed(0).padStart(5) + ' ms each, score ' +
    out[0].score + '-' + out[out.length - 1].score);
  return out;
}

console.log('building campaign');
const campaign = [];
for (const [N, band, want] of PLAN) {
  campaign.push(...collect(N, band, want, N + 'x' + N + ' ' + BAND_NAME[band]));
}

console.log('building spare pool');
const pool = {};
for (const N of [7, 8, 9, 10]) {
  pool[N] = [];
  for (let band = 0; band < 3; band++) {
    pool[N].push(collect(N, band, POOL_PER_BUCKET, 'pool ' + N + 'x' + N + ' ' + BAND_NAME[band]));
  }
}

// ------------------------------------------------- re-verify from the codec
console.log('re-verifying every puzzle from its codec string');
let checked = 0;
const check = p => {
  const s = C.encode(p);
  const d = C.decode(s);
  if (C.encode(d) !== s) throw new Error('codec round-trip failed: ' + s);
  if (C.countSolutions(d.N, d.regions, 3) !== 1) throw new Error('not unique: ' + s);
  if (!C.verify(d)) throw new Error('stored answer is not the solution: ' + s);
  const r = C.rate(d.N, d.regions);
  if (!r.solved) throw new Error('needs guessing: ' + s);
  if (r.band !== d.band) throw new Error('band drifted: ' + s);
  if (r.techBand !== d.band) throw new Error('labelled below its technique band: ' + s);
  // and it has to be followable, not just solvable: every step of the worked
  // explanation is a single, a subset or a touching step, each of them one
  // sentence about the board as it stands, and the chain reaches the last crown
  if (!C.followable(d.N, d.regions, d.sol)) throw new Error('needs a step the hint cannot say: ' + s);
  for (const w of C.chain(d.N, d.regions, d.sol)) {
    if (w.rule === 'flat' || w.rule === 'solution') throw new Error('a step with no reason to give: ' + s);
    if (/\bwould\b|\btry\b|\btries\b|\bsuppose\b|\bimagine\b|\bif\b/i.test(w.text)) throw new Error('a step that supposes: ' + w.text);
  }
  // the size profile is part of the band, so it gets checked here too
  const prof = C.SIZE_PROFILE[d.band];
  const min = C.minSize(d.N, d.regions);
  if (min < prof.minRegion) throw new Error('colour of ' + min + ' squares in a ' + BAND_NAME[d.band] + ': ' + s);
  const cv = C.sizeCV(d.N, d.regions);
  if (cv > prof.maxCV) throw new Error('sizes too spread (cv ' + cv.toFixed(2) + ') for ' + BAND_NAME[d.band] + ': ' + s);
  checked++;
  return s;
};

const campaignStrings = campaign.map(check);
const poolStrings = {};
for (const N of Object.keys(pool)) poolStrings[N] = pool[N].map(list => list.map(check));
console.log('  ' + checked + ' puzzles verified unique and guess-free');

// ------------------------------------------------------------------- write
const lines = [];
lines.push('/* Kitchen Table Queens — puzzles, generated by queens-tools/build.js.');
lines.push('   Each string is  size|colours|answer|difficulty|effort .');
lines.push('   Every one was re-checked for a single solution before it was written. */');
lines.push('(typeof window !== "undefined" ? window : globalThis).QUEENS_LEVELS = {');
lines.push('  campaign: [');
for (const s of campaignStrings) lines.push('    "' + s + '",');
lines.push('  ],');
lines.push('  pool: {');
for (const N of [7, 8, 9, 10]) {
  lines.push('    "' + N + '": [');
  for (const band of [0, 1, 2]) {
    lines.push('      [' + poolStrings[N][band].map(s => '"' + s + '"').join(', ') + '],');
  }
  lines.push('    ],');
}
lines.push('  },');
lines.push('};');
lines.push('if (typeof module === "object" && module.exports) module.exports = globalThis.QUEENS_LEVELS;');
lines.push('');

const target = path.join(__dirname, '..', 'levels.js');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, lines.join('\n'));

const bandsBySize = {};
for (const p of campaign) {
  bandsBySize[p.N] = bandsBySize[p.N] || [0, 0, 0];
  bandsBySize[p.N][p.band]++;
}
console.log('\nwrote ' + target);
console.log('  campaign ' + campaignStrings.length + ' levels, ' + (fs.statSync(target).size / 1024).toFixed(1) + ' kB total');
for (const N of [7, 8, 9, 10]) console.log('    ' + N + 'x' + N + '  easy/med/hard ' + bandsBySize[N].join('/'));
console.log('  spare pool ' + Object.values(poolStrings).flat(2).length + ' puzzles');

// ------------------------------------------------------------- what shipped
const all = campaign.concat(Object.values(pool).flat(2));
// which rules the shipped boards actually ask for
{
  const hist = {}, byBand = [{}, {}, {}];
  let steps = 0;
  for (const p of all) for (const w of C.chain(p.N, p.regions, p.sol)) {
    const key = w.rule === 'subset' ? 'subset k=' + w.k : w.rule;
    hist[key] = (hist[key] || 0) + 1;
    byBand[p.band][key] = (byBand[p.band][key] || 0) + 1;
    steps++;
  }
  const say = h => Object.keys(h).sort().map(k => k + ' ' + h[k]).join(', ');
  console.log('\n  rules over every shipped board (' + steps + ' steps)');
  console.log('    all      ' + say(hist));
  for (const band of [0, 1, 2]) console.log('    ' + BAND_NAME[band].padEnd(8) + say(byBand[band]));
}

console.log('\n  band    n  has 1-cell  has <=2-cell  avg min size  avg size CV');
for (const band of [0, 1, 2]) {
  const g = all.filter(p => p.band === band);
  const mins = g.map(p => Math.min.apply(null, p.sizes));
  const avg = a => (a.reduce((x, y) => x + y, 0) / a.length);
  console.log('  ' + BAND_NAME[band].padEnd(7) + String(g.length).padStart(3) +
    String(mins.filter(v => v <= 1).length).padStart(12) +
    String(mins.filter(v => v <= 2).length).padStart(14) +
    avg(mins).toFixed(2).padStart(14) +
    avg(g.map(p => C.sizeCV(p.N, p.regions))).toFixed(2).padStart(13));
}

console.log('\n  generation time, ms per puzzle');
console.log('  size     easy    medium      hard');
for (const N of [7, 8, 9, 10]) {
  const cell = band => {
    const rows = timing.filter(t => t.N === N && t.band === band);
    const n = rows.reduce((a, t) => a + t.n, 0);
    const ms = rows.reduce((a, t) => a + t.ms * t.n, 0) / n;
    return ms.toFixed(0).padStart(10);
  };
  console.log('  ' + String(N + 'x' + N).padEnd(7) + cell(0) + cell(1) + cell(2));
}
